#!/bin/bash

##############################################################
#
# 										Creado por: Manuel Gil
#
# Este script permite:
#
# - Este script permite el autodeploy de múltiples 
#   aplicaciones manejadas por GIT especificadas en 'DIRS'
# 	
#
# 														v1.0
##############################################################

DIRS=('/home/yeixon/dev/LorebiDashboard/ /home/yeixon/dev/RegistrationCard')

for project in $DIRS; do

	cd $project

	printf "updating `basename $project`... \n"
	git remote update

	UPSTREAM=${1:-@{u}}
	LOCAL=$(git rev-parse @)
	REMOTE=$(git rev-parse "$UPSTREAM")
	BASE=$(git merge-base @ "$UPSTREAM")

	printf "status: "
	if [[ $LOCAL = $REMOTE ]]; then
	    printf "up-to-date \n"
	elif [[ $LOCAL = $BASE ]]; then

	    printf "pulling... \n"

		git stash
		git pull

	elif [[ $REMOTE = $BASE ]]; then
	    printf "need to push \n"
	else
	    printf "diverged \n"
	fi

done