#!/bin/bash

##############################################################
#
# 					Creado por: Manuel Gil
#
# Este script permite:
#
# - Este script esta siendo ejecutado cada 5 minutos en busca
#   de actualizaciones para ser autodeployadas
#
##############################################################

cd /var/www/html/LorebiDashboard3
git remote update

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"

    sudo rm -r /var/www/html/LorebiDashboard-BACKUP
	sudo cp -r /var/www/html/LorebiDashboard3 /var/www/html/LorebiDashboard-BACKUP
	sudo rm -r img/hte

	git stash
	git pull

	sudo rm -r /var/www/html/LorebiDashboard3/img/hte
	sudo ln -s /home/ubuntu/hte /var/www/html/LorebiDashboard3/img
elif [ $REMOTE = $BASE ]; then
    echo "Need to push"
else
    echo "Diverged"
fi