#! /bin/bash
##########################################################
#
#									Creado por: Manuel Gil
#
#	Este script genera el backup (.sql) de una serie de bases
# 	de datos pasadas como argumentos al script. Después de 
# 	generado el .sql se aplica el restore en una base de datos
# 	espejo, ejemplo de uso:
# 	
# 	my-backup [ dbname1 dbname2 ... dbnameN ]
# 
# 	dbnameX: nombre de las bases de datos a respaldar
#
##########################################################

DIR="/home/"
USER="root"
PASS=""

if [[ $# -eq 0 ]]; then
	printf "error: Argumentos inválidos \n\n"

	printf "my-backup usage: my-backup [ dbname1 dbname2 ... dbnameN ] \n\n"

	printf "	dbnameX: Nombre de las bases de datos a respaldar \n\n"

	exit
fi

mkdir -p $DIR

for db in $@; do

	printf "Respaldando ${db} en ${DIR}${db}_`date +%d-%m-%Y`.sql \n"
	
	# REALIZO EL BACKUP A LA BASE DE DATOS DE PRODUCCION
	mysqldump -u $USER --password=$PASS --routines --opt $db > $DIR$db'_'`date +%d-%m-%Y`.sql

	printf "Creando base de datos de respaldo si no existe \n"

	# SI LA BASE DE DATOS DE RESPALDO NO EXISTE LA CREO
	mysql -u $USER --password=$PASS -e "create database if not exists ${db}_backup"

	printf "Restaurando respaldo en ${db}_backup \n"

	# EJECUTO EL RESTORE CREADO ANTERIORMENTE EN LA BASE DE DATOS DE RESPALDO
	mysql -u $USER --password=$PASS $db'_'backup < $DIR$db'_'`date +%d-%m-%Y`.sql

done

exit